### ISSUE TITLE
VR mode seems "zoomed in" with DK2

### ISSUE THREAD

**Issue by jzitelli** [capnmidnight/Primrose#72] opened 2016-01-24 05:49 UTC
Hey capnmidnight, I'm experiencing what looks like a very "zoomed in" VR image when I enter VR mode with DK2, on both firefox nightly and the chromium 0.8 DK2 build... it happens in the current master branch (I didn't check dev) and also at www.primrosevr.com.  Are you seeing this as well when using DK2?

**Comment by capnmidnight** [comment] 2016-01-24 18:52
I've noticed what you're referring to in the past. It even seems like the ground is too close, too, like you're not standing high enough. But I'm not quite sure what exactly the problem is. There are three things it would most likely be: incorrect FOV, incorrect IPD camera translation, or incorrect object scale. 

The FOV and the IPD values are both taken from the WebVR API. It should be the same as everyone else's demos. The scale in Primrose is 1 unit = 1 meter. The demos generally have a lack of depth and sizing cues like shadows and familiar objects. So it's difficult to tease apart the different factors given my current demos. I'm pretty confident that the IPD and avatar height are correct, because they should all be in the same units.

I'm not confident that the FOV setup is correct. We need to compare it against THREE.js' VREffect class (I don't want to use VREffect directly because it won't integrate with my Input library, which means it won't easily serialize over a network connection).

One indication that makes me feel it's just making objects too large and spacing them too far apart is that the avatar walking speed is currently 2 m/s. Normal, average, human walking speed is between 0.9 and 1.3 m/s. I've had it higher than 2 in the past, 3 often felt more comfortable, just in terms of being able to get between objects.

Another indication: in trying to figure this out a few weeks ago, I played with the eye translation and making it whole multiples of the value reported by the WebVR API. It did improve the feeling of height above the ground. My feeling is that doing that kind of jiggering of the value changed the ratio of units in inverse relationship: 2x IPD distance = 0.5m per unit. The IPD is basically the only fixed-reference we would be able to give people: however far apart their eyes are is fixed, and the brain will fuse the images and reconsider the size and distance of things based thereof.

So perhaps the easiest test that can be done right now is to create a test scene with very familiar objects within it. Chairs, tables, desk items, etc. I think an indoor scene would be easier and more familiar than an outdoor scene.

I'm trying to be good and not work on any new features until I finish the documentation backlog, then stick to a strict policy of making sure the documentation is always up to date with any new code I write.

**Comment by capnmidnight** [comment] 2016-03-13 21:19
The latest code in the dev branch is now using a new FOV to Projection Matrix calculation. Perhaps this helps?

**Comment by jzitelli** [comment] 2016-03-18 04:33
I just tried with the latest dev branch... in the most recent Oculus WebVR Chromium I seem to always get the "aww snap webgl" screen a moment after the page loads!

With the latest Firefox Nightly, I still seem to have some strange warping / distortion happening in the HMD.  I captured a SBS video of what is mirrored to the monitor, to hopefully demonstrate the issue in 3D when viewed with e.g. Virtual Desktop, but it looks fine when viewing the capture.  It leads me to believe that whatever the problem is, it is only affecting the actual HMD image...  I tried looking around in the code a while ago, but I was a bit lost, seems like a lot has changed!  If you could point me to what might be the relevant files, I might be able to figure this out...

**Comment by capnmidnight** [comment] 2016-03-18 14:16
Yep, that's my fault. In the process of building a full GUI framework, I broke the 2D use-case for the text editor, which also breaks the main index page. Please set your startup page to be examples/editor3d/index.html for now, and hopefully I'll have the 2D editor fixed by the end of today.

For the most part, things are the same. I've renamed VRApplication to BrowserEnvironment to reflect it's purpose a little better (Eventually, there will also be a ServerEnvironment, with confederation built in between the them, but that's getting ahead of myself right now), but the code within it is largely unchanged. Changes to the WebVR API necessitated changes to the VR Input class, but now the overall design is better, I think. The MotionInput class has changed completely, to become a polyfill for Google Cardboard-based systems running non-WebVR enabled browsers, with the data flowing through VRInput, rather than BrowserEnvironment-nee-VRApplication doing the aggregation itself.

The parts that deal directly with the camera projection are here:
* non-WebVR FOV setting: https://github.com/capnmidnight/Primrose/blob/dev/src/fx/input/vr/CardboardVRDisplay.js#L29-L34
* legacy-WebVR FOV setting: https://github.com/capnmidnight/Primrose/blob/dev/src/fx/input/vr/LegacyVRDisplay.js#L35
* WebVR 1.0 FOV setting is just used directly: https://github.com/capnmidnight/Primrose/blob/dev/src/fx/input/VR.js#L239
* FOV gets converted to projection matrix here: https://github.com/capnmidnight/Primrose/blob/dev/src/fx/input/VR.js#L207-L234
* And projection matrix gets applied here: https://github.com/capnmidnight/Primrose/blob/dev/src/fx/BrowserEnvironment.js#L287-L290

In particular, in that last link, I'm pretty sure there is a bug that the IPD offset is not being applied correctly given the camera quaternion for head orientation. When you tilt your head sideways (rotate about Z-axis), the stereo image becomes misaligned in the Y-axis.

**Comment by capnmidnight** [comment] 2016-03-20 02:31
BTW, I did fix that issue with the 2D editor not working, and I also fixed that issue with the IPD offset. Finally, I increased the FOV for Google Cardboard devices on non-WebVR browsers.

**Closed** 2016-04-03 13:21 UTC

**Comment by capnmidnight** [comment] 2016-04-03 13:27
Trello card https://trello.com/c/47qch9D3
