### ISSUE TITLE
No select, copy, paste, undo, select all

### ISSUE THREAD

**Issue by tianshuo** [capnmidnight/Primrose#17] opened 2015-01-04 04:11 UTC
That leaves this as an  texteditor unusable.

**Comment by capnmidnight** [comment] 2015-01-04 04:13
Thanks for the report. However, this is a duplicate of https://github.com/capnmidnight/Primrose/issues/12

**Comment by tianshuo** [comment] 2015-01-04 04:49
I didn't see select.. but since you have to select to copy and cut, I guess this is included

**Comment by tianshuo** [comment] 2015-01-10 10:38
@capnmidnight undo doesn't work

**Comment by capnmidnight** [comment] 2015-01-10 13:51
What key combo are you using for Undo? I see that you are from China, perhaps there is a difference between what we use for the Undo command? On my US English keyboard, I hit CTRL+Z for Undo, with Z being keyCode 90. If you could open the JavaScript console in your browser, focus on the editor, and report the text the console prints when you hit your key combo, that would help me narrow this down.

I have a plan in the works to have much wider international keyboard support, but at this moment it just assumes that everyone has to hit their equivalent of the Z key.

Anyway, thanks again for the report.

**Comment by tianshuo** [comment] 2015-01-15 03:07
I'm using us keyboard as well, but maybe the problem is mac uses command instead of control. Using inspector, I got:
`event.hotkey="meta-z"`

**Comment by capnmidnight** [comment] 2015-01-15 03:48
aaah, that would do it. i have a fix for this in the works, coming as part
of the full international keyboard support.

**Comment by capnmidnight** [comment] 2015-01-16 02:21
Okay, I think I have all of the OSX keyboard commands working. It's a little difficult for me to test, I don't have an OSX machine of my own, but everything seemed to work on my wife's laptop.

**Closed** 2015-01-30 10:41 UTC
Labels: bug
